version: '3'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack.dev
    ports:
      - "8080:8080"
      - "4567-4583:4567-4583"
    environment:
      DEFAULT_REGION: us-east-1
      SERVICES: sqs:4576
    volumes:
      - "./build/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"